window.WorkflowView = {
  template: `
    <div class="workflow-view page-shell">
      <style>
        .page-shell{font-family:"Microsoft YaHei",Arial,sans-serif;color:#1f2937}.page-header,.workflow-card-grid,.workflow-config-grid,.approval-levels,.detail-grid,.timeline-list{display:grid;gap:14px}.page-header{margin-bottom:16px}.page-title{margin:0;font-size:28px}.page-subtitle,.reviewed-meta,.timeline-meta,.config-tip{color:#64748b;font-size:12px}
        .panel-card,.approval-card,.config-card{background:#fff;border:1px solid #e5e7eb;border-radius:14px;box-shadow:0 8px 24px rgba(15,23,42,.05);padding:16px}.tab-bar{display:flex;gap:8px;margin-bottom:16px;flex-wrap:wrap}.tab-btn{border:1px solid #cbd5e1;background:#fff;border-radius:999px;padding:8px 14px;cursor:pointer}.tab-btn.active{background:#2563eb;color:#fff;border-color:#2563eb}
        .workflow-card-grid,.workflow-config-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.approval-card-head,.panel-header,.modal-header,.modal-footer,.approval-actions{display:flex;justify-content:space-between;gap:12px;align-items:center}.approval-card-head h3,.panel-header h3,.modal-header h3{margin:0}.approval-meta{display:flex;justify-content:space-between;gap:12px;margin:10px 0;font-size:13px;color:#475569}.approval-desc{min-height:54px;padding:12px;border-radius:12px;background:#f8fafc;color:#334155;margin-bottom:12px}
        .btn{border:none;border-radius:10px;padding:10px 14px;cursor:pointer;font-weight:600}.btn-success{background:#16a34a;color:#fff}.btn-danger{background:#dc2626;color:#fff}.btn-secondary{background:#e2e8f0;color:#0f172a}.btn-primary{background:#2563eb;color:#fff}.btn-text{background:transparent;color:#2563eb;padding:0}
        .priority-badge,.status-badge,.approval-level{display:inline-flex;align-items:center;justify-content:center;border-radius:999px;padding:4px 10px;font-size:12px;font-weight:700}.priority-urgent{background:#fee2e2;color:#b91c1c}.priority-high{background:#ffedd5;color:#c2410c}.priority-medium{background:#e0f2fe;color:#0369a1}.priority-low{background:#f1f5f9;color:#475569}.status-pending{background:#fef3c7;color:#b45309}.status-review{background:#dbeafe;color:#1d4ed8}.status-online{background:#dcfce7;color:#15803d}.status-rejected{background:#fee2e2;color:#b91c1c}.urgency-text{color:#dc2626;font-weight:700}
        .table-wrapper{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:12px;border-bottom:1px solid #e5e7eb;text-align:left;font-size:13px}th{background:#f8fafc;color:#475569}.table-row-clickable{cursor:pointer}.table-row-clickable:hover{background:#f8fafc}.reviewed-list{display:grid;gap:12px}.reviewed-item{display:flex;justify-content:space-between;gap:12px;padding:12px;border-radius:12px;background:#f8fafc;border:1px solid #e2e8f0}.reviewed-title{font-weight:700}.config-stages{background:#f8fafc;border-radius:12px;padding:12px;margin:12px 0}
        .modal-mask{position:fixed;inset:0;background:rgba(15,23,42,.42);display:flex;align-items:center;justify-content:center;padding:20px;z-index:1000}.modal-container{width:min(840px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:16px}.modal-large{width:min(980px,100%)}.modal-header,.modal-footer{padding:16px 18px;border-bottom:1px solid #e5e7eb}.modal-footer{border-top:1px solid #e5e7eb;border-bottom:none;justify-content:flex-end}.modal-body{padding:18px}.detail-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.detail-grid label{display:block;color:#64748b;font-size:12px;margin-bottom:4px}.detail-span-2{grid-column:span 2}
        .approval-levels{grid-template-columns:repeat(4,minmax(0,1fr));margin-bottom:16px}.approval-level{background:#e2e8f0;color:#475569;padding:8px 0}.approval-level.active{background:#dbeafe;color:#1d4ed8}.form-item{display:grid;gap:6px;margin-bottom:14px}input,textarea{width:100%;box-sizing:border-box;border:1px solid #cbd5e1;border-radius:10px;padding:10px 12px;font-size:13px}.required{color:#dc2626}
        .pipeline-diagram{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:18px}.pipeline-step{border:1px solid #e2e8f0;border-radius:12px;padding:14px;text-align:center;background:#f8fafc}.pipeline-step.done{background:#dcfce7;border-color:#bbf7d0}.pipeline-step.active{background:#dbeafe;border-color:#bfdbfe}.pipeline-step.rejected{background:#fee2e2;border-color:#fecaca}.pipeline-icon{width:36px;height:36px;margin:0 auto 10px;border-radius:50%;display:flex;align-items:center;justify-content:center;background:#fff;font-weight:700}
        .timeline-item{display:grid;grid-template-columns:16px 1fr;gap:12px;padding:12px;border-radius:12px;background:#f8fafc;border:1px solid #e2e8f0}.timeline-dot{width:12px;height:12px;border-radius:50%;margin-top:4px}.timeline-dot.done{background:#16a34a}.timeline-dot.active{background:#2563eb}.timeline-dot.pending{background:#f59e0b}.timeline-dot.rejected{background:#dc2626}.empty-state{text-align:center;color:#64748b;padding:24px 12px}
        @media (max-width:1100px){.workflow-card-grid,.workflow-config-grid,.pipeline-diagram{grid-template-columns:1fr 1fr}}@media (max-width:760px){.workflow-card-grid,.workflow-config-grid,.pipeline-diagram,.detail-grid,.approval-levels{grid-template-columns:1fr}}
      </style>
      <div class="page-header"><div><h2 class="page-title">审核流转管理</h2><div class="page-subtitle">集中处理待审事项、流程追踪与模板配置</div></div></div>
      <div class="tab-bar"><button class="tab-btn" :class="{ active: activeTab === 'pending' }" @click="activeTab = 'pending'">待我审核({{ pendingApprovals.length }})</button><button class="tab-btn" :class="{ active: activeTab === 'reviewed' }" @click="activeTab = 'reviewed'">我已审核</button><button class="tab-btn" :class="{ active: activeTab === 'all' }" @click="activeTab = 'all'">全部流程</button><button class="tab-btn" :class="{ active: activeTab === 'config' }" @click="activeTab = 'config'">流程配置</button></div>
      <div v-show="activeTab === 'pending'" class="workflow-card-grid"><div v-for="item in pendingApprovals" :key="item.id + item.currentStage" class="approval-card"><div class="approval-card-head"><h3>{{ item.title }}</h3><span :class="['priority-badge', priorityClass(item.priority)]">{{ priorityText(item.priority) }}</span></div><div class="approval-meta"><span>环节：{{ item.currentStage }}</span><span>提交人：{{ item.submitter || '--' }}</span></div><div class="approval-meta"><span>截止：{{ formatDate(item.dueDate) }}</span><span class="urgency-text">{{ urgencyText(item.priority, item.dueDate) }}</span></div><div class="approval-desc">{{ item.summary || item.description || '暂无需求摘要' }}</div><div class="approval-actions"><button class="btn btn-success" @click="openDecisionModal(item, 'approve')">审批通过</button><button class="btn btn-danger" @click="openDecisionModal(item, 'reject')">驳回</button><button class="btn btn-secondary" @click="openFlowDetail(item)">查看详情</button></div></div><div v-if="!pendingApprovals.length" class="panel-card empty-state">当前暂无待我审核事项</div></div>
      <div v-show="activeTab === 'reviewed'" class="panel-card"><div class="panel-header"><h3>我已审核</h3><span class="page-subtitle">{{ reviewedApprovals.length }} 条记录</span></div><div class="reviewed-list"><div v-for="item in reviewedApprovals" :key="item.id + item.updatedAt" class="reviewed-item"><div><div class="reviewed-title">{{ item.title }}</div><div class="reviewed-meta">{{ item.currentStage }} · {{ formatDateTime(item.updatedAt) }}</div></div><span :class="['status-badge', statusClass(item.status)]">{{ statusText(item.status) }}</span></div><div v-if="!reviewedApprovals.length" class="empty-state">暂无已审核记录</div></div></div>
      <div v-show="activeTab === 'all'" class="panel-card"><div class="panel-header"><h3>全部流程</h3><span class="page-subtitle">运行中 {{ activeFlowCount }} / 已结束 {{ finishedFlowCount }}</span></div><div class="table-wrapper"><table><thead><tr><th>需求编号</th><th>需求名称</th><th>当前环节</th><th>当前审核人</th><th>状态</th><th>更新时间</th></tr></thead><tbody><tr v-for="item in allFlows" :key="item.id" class="table-row-clickable" @click="openFlowDetail(item)"><td>{{ item.id }}</td><td>{{ item.title }}</td><td>{{ item.currentStage }}</td><td>{{ item.currentReviewer || '--' }}</td><td><span :class="['status-badge', statusClass(item.status)]">{{ statusText(item.status) }}</span></td><td>{{ formatDateTime(item.updatedAt || item.submitDate) }}</td></tr><tr v-if="!allFlows.length"><td colspan="6" class="empty-state">暂无流程数据</td></tr></tbody></table></div></div>
      <div v-show="activeTab === 'config'" class="workflow-config-grid"><div v-for="template in workflowTemplates" :key="template.name" class="config-card"><div class="panel-header"><h3>{{ template.name }}</h3><button class="btn btn-text" @click="openConfigModal(template)">编辑</button></div><div class="config-stages">{{ template.stagesText }}</div><div>总 SLA：{{ template.sla }}</div><div class="page-subtitle" style="margin-top:8px">适用场景：{{ template.scenario }}</div></div></div>
      <div v-if="decisionModal.visible && decisionModal.item" class="modal-mask"><div class="modal-container"><div class="modal-header"><h3>{{ decisionModal.action === 'approve' ? '审批通过' : '驳回需求' }}</h3><button class="btn btn-text" @click="closeDecisionModal()">关闭</button></div><div class="modal-body"><div class="detail-grid"><div class="detail-span-2"><label>需求摘要</label><div>{{ decisionModal.item.title }}</div></div><div><label>需求编号</label><div>{{ decisionModal.item.id }}</div></div><div><label>当前环节</label><div>{{ decisionModal.item.currentStage }}</div></div><div><label>提交人</label><div>{{ decisionModal.item.submitter || '--' }}</div></div><div><label>截止日期</label><div>{{ formatDate(decisionModal.item.dueDate) }}</div></div></div><div class="approval-levels"><span v-for="level in approvalLevels" :key="level" :class="['approval-level', { active: isLevelActive(level, decisionModal.item.currentStage) }]">{{ level }}</span></div><div class="form-item"><label>审批意见 <span v-if="decisionModal.action === 'reject'" class="required">*</span></label><textarea rows="4" v-model.trim="decisionModal.opinion" placeholder="请输入审批意见"></textarea></div><div v-if="needsTechnicalFields(decisionModal.item.currentStage)" class="detail-grid"><div class="form-item"><label>性能预估</label><input type="text" v-model.trim="decisionModal.performanceEstimate" placeholder="日增量 / 峰值QPS"></div><div class="form-item"><label>索引方案</label><input type="text" v-model.trim="decisionModal.indexPlan" placeholder="核心索引设计"></div></div><div v-if="needsComplianceFields(decisionModal.item.currentStage)" class="form-item"><label>合规控制说明</label><input type="text" v-model.trim="decisionModal.riskControl" placeholder="脱敏字段、权限隔离、留痕控制"></div></div><div class="modal-footer"><button class="btn btn-secondary" @click="closeDecisionModal()">取消</button><button :class="decisionModal.action === 'approve' ? 'btn btn-success' : 'btn btn-danger'" @click="submitDecision()">确认{{ decisionModal.action === 'approve' ? '通过' : '驳回' }}</button></div></div></div>
      <div v-if="detailModal.visible && detailModal.item" class="modal-mask"><div class="modal-container modal-large"><div class="modal-header"><h3>流程详情 - {{ detailModal.item.title }}</h3><button class="btn btn-text" @click="closeFlowDetail()">关闭</button></div><div class="modal-body"><div class="pipeline-diagram"><div v-for="stage in detailPipeline" :key="stage.name" :class="['pipeline-step', stage.state]"><div class="pipeline-icon">{{ stage.icon }}</div><div>{{ stage.name }}</div><div class="page-subtitle">{{ stage.statusText }}</div></div></div><div class="timeline-list"><div v-for="(record, index) in detailTimeline" :key="index" class="timeline-item"><div :class="['timeline-dot', record.state]"></div><div><div>{{ record.stage }} · {{ record.action }}</div><div class="timeline-meta">{{ record.actor || '系统' }} · {{ formatDateTime(record.time) }}</div><div>{{ record.comment || '暂无说明' }}</div></div></div><div v-if="!detailTimeline.length" class="empty-state">暂无审批动作记录</div></div></div></div></div>
      <div v-if="configModal.visible && configModal.template" class="modal-mask"><div class="modal-container"><div class="modal-header"><h3>编辑流程模板</h3><button class="btn btn-text" @click="configModal.visible = false">关闭</button></div><div class="modal-body"><div class="detail-grid"><div class="detail-span-2"><label>模板名称</label><div>{{ configModal.template.name }}</div></div><div class="detail-span-2"><label>阶段配置</label><div>{{ configModal.template.stagesText }}</div></div><div><label>总 SLA</label><div>{{ configModal.template.sla }}</div></div><div><label>适用场景</label><div>{{ configModal.template.scenario }}</div></div></div><p class="config-tip">当前为演示界面：编辑按钮提供完整交互入口，后续可接入后端配置中心。</p></div><div class="modal-footer"><button class="btn btn-secondary" @click="configModal.visible = false">关闭</button><button class="btn btn-primary" @click="configModal.visible = false">确认</button></div></div></div>
    </div>
  `,
  data: function () { return { activeTab: 'pending', currentUser: {}, approvals: [], decisionModal: { visible: false, action: 'approve', item: null, opinion: '', performanceEstimate: '', indexPlan: '', riskControl: '' }, detailModal: { visible: false, item: null }, configModal: { visible: false, template: null }, approvalLevels: ['业务', '数据', '技术', '合规'] }; },
  computed: {
    pendingApprovals: function () { return this.approvals.filter(function (item) { return this.statusText(item.status) === '审核中' && item.mine; }, this); },
    reviewedApprovals: function () { return this.approvals.filter(function (item) { return item.handledByMe || (item.mine && /已上线|已驳回/.test(this.statusText(item.status))); }, this); },
    allFlows: function () { return this.approvals; },
    activeFlowCount: function () { return this.approvals.filter(function (item) { return !/已上线|已驳回/.test(this.statusText(item.status)); }, this).length; },
    finishedFlowCount: function () { return this.approvals.length - this.activeFlowCount; },
    workflowTemplates: function () { return [{ name: 'Standard Process', stagesText: 'Business(1d) → Data(2d) → Technical(2d) → Compliance(3d)', sla: '8 个工作日', scenario: '常规报表、经营分析、专题数据服务' }, { name: 'Fast Track', stagesText: 'Data(1d) → Technical(1d) [skip business and compliance]', sla: '2 个工作日', scenario: '简单字段新增、低风险变更、紧急修复' }, { name: 'Regulatory Reporting', stagesText: 'Compliance(1d) → Business(1d) → Data(2d) → Technical(2d)', sla: '6 个工作日', scenario: '监管报送、审计检查、敏感数据输出' }]; },
    detailPipeline: function () { if (!this.detailModal.item) return []; var current = this.detailModal.item.currentStage; var status = this.statusText(this.detailModal.item.status); var stages = ['业务审核', '数据审核', '技术审核', '合规审核']; var idx = Math.max(0, stages.indexOf(current)); var icons = { '业务审核': '业', '数据审核': '数', '技术审核': '技', '合规审核': '合' }; return stages.map(function (name, i) { var state = i < idx ? 'done' : i === idx ? 'active' : 'pending'; if (status === '已驳回' && i === idx) state = 'rejected'; if (status === '已上线') state = 'done'; return { name: name, icon: icons[name], state: state, statusText: state === 'done' ? '已完成' : state === 'active' ? '处理中' : state === 'rejected' ? '已驳回' : '待处理' }; }); },
    detailTimeline: function () { return this.detailModal.item ? (this.detailModal.item.timeline || []) : []; }
  },
  methods: {
    loadData: function () { var source = window.MockData || {}; this.currentUser = JSON.parse(JSON.stringify(source.currentUser || source.user || {})); this.approvals = this.normalizeApprovals(source.workflows || source.workflowList || source.approvals || [], source.requirements || source.requirementList || source.demands || []); },
    normalizeApprovals: function (workflowList, requirementList) { var reqMap = {}; (requirementList || []).forEach(function (req, idx) { reqMap[req.id || req.code || req.requirementId || ('REQ-' + idx)] = req; }); if ((workflowList || []).length) return workflowList.map(function (item, idx) { return this.buildApprovalRecord(item, reqMap[item.id || item.code || item.requirementId || ('REQ-' + idx)] || {}, idx); }, this).sort(this.sortByDateDesc); return (requirementList || []).map(function (item, idx) { return this.buildApprovalFromRequirement(item, idx); }, this).sort(this.sortByDateDesc); },
    buildApprovalRecord: function (item, req, idx) { var me = (this.currentUser && this.currentUser.name) || ''; var reviewer = item.currentReviewer || item.approver || item.assignee || req.currentReviewer || ''; return { id: item.id || item.code || item.requirementId || req.id || ('WF-' + idx), title: item.title || req.title || req.name || '未命名需求', summary: item.summary || req.description || req.desc || '', description: req.description || req.desc || '', priority: item.priority || req.priority || req.level || '中', submitter: item.submitter || req.submitter || req.creator || '', dueDate: item.dueDate || req.dueDate || req.deadline || '', currentStage: this.normalizeStage(item.currentStage || item.stage || item.stepName || req.currentStage || '业务审核'), currentReviewer: reviewer, status: item.status || item.currentStatus || req.status || '审核中', submitDate: item.submitDate || req.submitDate || req.createdAt || '', updatedAt: item.updatedAt || item.updateTime || req.updatedAt || '', mine: !reviewer || reviewer === me, handledByMe: (item.operator || item.updatedBy || '') === me, timeline: this.normalizeTimeline(item.timeline || item.actions || req.timeline || req.workflowTimeline || []) }; },
    buildApprovalFromRequirement: function (req, idx) { var me = (this.currentUser && this.currentUser.name) || '当前审核人'; return { id: req.id || req.code || req.requirementId || ('REQ-' + idx), title: req.title || req.name || '未命名需求', summary: req.description || req.desc || '', description: req.description || req.desc || '', priority: req.priority || req.level || '中', submitter: req.submitter || req.creator || '', dueDate: req.dueDate || req.deadline || '', currentStage: this.normalizeStage(req.currentStage || req.stage || '业务审核'), currentReviewer: req.currentReviewer || me, status: req.status || '审核中', submitDate: req.submitDate || req.createdAt || '', updatedAt: req.updatedAt || req.submitDate || '', mine: true, handledByMe: false, timeline: this.normalizeTimeline(req.timeline || req.workflowTimeline || []) }; },
    normalizeTimeline: function (list) { return (list || []).map(function (item) { return { stage: this.normalizeStage(item.stage || item.stepName || item.name || '流程节点'), action: item.action || this.statusText(item.status || item.result || '待处理'), actor: item.actor || item.owner || item.approver || '', time: item.time || item.updatedAt || item.timestamp || '', comment: item.comment || item.opinion || '', state: this.timelineState(item.status || item.result || item.action || '') }; }, this); },
    normalizeStage: function (stage) { var s = String(stage || ''); if (/合规/.test(s)) return '合规审核'; if (/技术|脚本|开发/.test(s)) return '技术审核'; if (/数据/.test(s)) return '数据审核'; return '业务审核'; },
    statusText: function (status) { var s = String(status || ''); if (/驳回|reject|fail/i.test(s)) return '已驳回'; if (/通过|上线|完成|success|online/i.test(s)) return '已上线'; if (/审核|审批|review|develop|test/i.test(s)) return '审核中'; return '待处理'; },
    statusClass: function (status) { var s = this.statusText(status); return s === '已上线' ? 'status-online' : s === '已驳回' ? 'status-rejected' : s === '审核中' ? 'status-review' : 'status-pending'; },
    priorityText: function (priority) { var s = String(priority || ''); if (/P0|紧急/i.test(s)) return '紧急'; if (/P1|高/i.test(s)) return '高'; if (/P3|低/i.test(s)) return '低'; return '中'; },
    priorityClass: function (priority) { var s = this.priorityText(priority); return s === '紧急' ? 'priority-urgent' : s === '高' ? 'priority-high' : s === '低' ? 'priority-low' : 'priority-medium'; },
    urgencyText: function (priority, dueDate) { if (this.priorityText(priority) === '紧急') return '高优先级'; var d = new Date(dueDate); if (!isNaN(d.getTime()) && Math.ceil((d.getTime() - Date.now()) / 86400000) <= 1) return '即将到期'; return '正常'; },
    isLevelActive: function (level, stage) { return String(stage || '').indexOf(level) > -1; },
    needsTechnicalFields: function (stage) { return /技术/.test(stage || ''); },
    needsComplianceFields: function (stage) { return /合规/.test(stage || ''); },
    openDecisionModal: function (item, action) { this.decisionModal = { visible: true, action: action, item: item, opinion: '', performanceEstimate: '', indexPlan: '', riskControl: '' }; },
    closeDecisionModal: function () { this.decisionModal.visible = false; this.decisionModal.item = null; },
    submitDecision: function () { var item = this.decisionModal.item; if (!item) return; if (this.decisionModal.action === 'reject' && !this.decisionModal.opinion) return; var now = new Date().toISOString(); var actor = (this.currentUser && this.currentUser.name) || '当前审核人'; item.timeline = item.timeline || []; item.timeline.unshift({ stage: item.currentStage, action: this.decisionModal.action === 'approve' ? '审批通过' : '驳回', actor: actor, time: now, comment: this.decisionModal.opinion || (this.decisionModal.action === 'approve' ? '同意推进' : '驳回处理'), state: this.decisionModal.action === 'approve' ? 'done' : 'rejected' }); item.updatedAt = now; item.handledByMe = true; item.mine = false; if (this.decisionModal.action === 'approve') { if (item.currentStage === '业务审核') { item.currentStage = '数据审核'; item.currentReviewer = '数据审核人'; item.status = '审核中'; } else if (item.currentStage === '数据审核') { item.currentStage = '技术审核'; item.currentReviewer = '技术审核人'; item.status = '审核中'; } else if (item.currentStage === '技术审核') { item.currentStage = '合规审核'; item.currentReviewer = '合规审核人'; item.status = '审核中'; } else { item.currentStage = '流程结束'; item.currentReviewer = ''; item.status = '已上线'; } } else { item.status = '已驳回'; item.currentReviewer = ''; } this.closeDecisionModal(); },
    openFlowDetail: function (item) { this.detailModal.visible = true; this.detailModal.item = item; },
    closeFlowDetail: function () { this.detailModal.visible = false; this.detailModal.item = null; },
    openConfigModal: function (template) { this.configModal.visible = true; this.configModal.template = template; },
    timelineState: function (status) { var s = String(status || ''); if (/驳回|reject/i.test(s)) return 'rejected'; if (/通过|完成|success|上线/i.test(s)) return 'done'; if (/审核|待|pending|review/i.test(s)) return 'active'; return 'pending'; },
    formatDate: function (value) { if (!value) return '--'; var d = new Date(value); if (isNaN(d.getTime())) return value; return d.getFullYear() + '-' + String(d.getMonth() + 1).padStart(2, '0') + '-' + String(d.getDate()).padStart(2, '0'); },
    formatDateTime: function (value) { if (!value) return '--'; var d = new Date(value); if (isNaN(d.getTime())) return value; return this.formatDate(d) + ' ' + String(d.getHours()).padStart(2, '0') + ':' + String(d.getMinutes()).padStart(2, '0'); },
    sortByDateDesc: function (a, b) { return new Date(b.updatedAt || b.submitDate || 0).getTime() - new Date(a.updatedAt || a.submitDate || 0).getTime(); }
  },
  mounted: function () { this.loadData(); }
};
